In [1]:
import numpy as np

In [2]:
inputs = np.array([1.0, 2.0, 3.0, 2.5])  
weights = np.array([0.2, 0.8, -0.5, 1.0])
bias = 2.0

output = np.dot(inputs, weights) + bias
print(output)

4.8


In [3]:
inputs = np.array([1, 2, 3, 2.5])

weights = np.array([
    [0.2, 0.8, -0.5, 1], # weights[0]
    [0.5, -0.91, 0.26, -0.5], # weights[1]
    [-0.26, -0.27, 0.17, 0.87] # weights[2]
])

biases = np.array([2, 3, 0.5])

outputs = [0] * len(weights)

for i in range(0, len(weights)):
    outputs[i] = np.dot(weights[i], inputs) + biases[i]
print(outputs)

outputs = np.dot(weights, inputs) + biases
print(outputs)

outputs = np.dot(inputs, weights.T) + biases
print(outputs)

[np.float64(4.8), np.float64(1.21), np.float64(2.385)]
[4.8   1.21  2.385]
[4.8   1.21  2.385]


#### Multiple Inputs - Batch Data

In [4]:
batch = np.array([
    [1, 2, 3, 2.5],
    [2, 5, -1, 2.0],
    [-1.5, 2.7, 3.3, -0.8]
])

weights = np.array([
    [0.2, 0.8, -0.5, 1],
    [0.5, -0.91, 0.26, -0.5],
    [-0.26, -0.27, 0.17, 0.87]
])

biases = np.array([2.0, 3.0, 0.5])

outputs = np.dot(batch, weights.T) + biases
print(outputs)

[[ 4.8    1.21   2.385]
 [ 8.9   -1.81   0.2  ]
 [ 1.41   1.051  0.026]]
