In [1]:
import numpy as np

### The Base Inputs

In [2]:
inputs = np.array([
    [1, 2, 3, 2.5],
    [2.0, 5.0, -1.0, 2],
    [-1.5, 2.7, 3.3, -0.8]
])

### Weights for the first layer

In [3]:
weights1 = np.array([
    [0.2, 0.8, -0.5, 1],
    [0.5, -0.91, 0.26, -0.5],
    [-0.26, -0.27, -0.17, 0.87]
])

### Weights for the second layer

In [4]:
weights2 = np.array([
    [0.1, -0.14, 0.5],
    [-0.5, 0.12, -0.33],
    [-0.44, 0.73, -0.13]
])

### Biases

In [5]:
biases1 = [2, 3, 0.5]
biases2 = [-1, 2, -0.5]

```
From the above data, it is deduced that the first layer has four neurons and the second layer has 3 neurons
```

In [6]:
layer1_outputs = np.dot(inputs, weights1.T) + biases1

In [7]:
print(layer1_outputs)

[[ 4.8    1.21   1.365]
 [ 8.9   -1.81   0.54 ]
 [ 1.41   1.051 -1.096]]


In [8]:
layer2_outputs = np.dot(layer1_outputs, weights2.T) + biases2

In [9]:
print(layer2_outputs)

[[-0.0069  -0.70525 -1.90615]
 [ 0.4134  -2.8454  -5.8075 ]
 [-1.55414  1.7828  -0.21069]]


### Sample Assignments

In [10]:
inputs = np.array([
    [1, 2, 3, 4],
    [1, 2, 3, 4],
    [3, 1, 35, 6]
])

w1 = np.random.rand(3, 4)
w2 = np.random.rand(3, 3)
w3 = np.random.rand(3, 3)
w4 = np.random.rand(3, 3)
w5 = np.random.rand(3, 3)

b1 = np.random.rand(3)
b2 = np.random.rand(3)
b3 = np.random.rand(3)
b4 = np.random.rand(3)
b5 = np.random.rand(3)

In [11]:
l1 = np.dot(inputs, w1.T) + b1
print(l1)

[[ 5.15684917  4.07622431  4.67977   ]
 [ 5.15684917  4.07622431  4.67977   ]
 [37.67280552 18.7172414  22.94797363]]


In [12]:
l2 = np.dot(l1, w2.T) + b2 
print(l2)

[[ 6.142915    5.53293167  9.84749805]
 [ 6.142915    5.53293167  9.84749805]
 [32.33064873 35.73568856 52.3858005 ]]


In [13]:
l3 = np.dot(l2, w3.T) + b3
print(l3)

[[12.34967344  5.39136731  7.22310836]
 [12.34967344  5.39136731  7.22310836]
 [68.81840426 28.38446097 36.39422162]]


In [14]:
l4 = np.dot(l3, w4.T) + b4
print(l4)

[[15.01593707 14.98475364 18.83935253]
 [15.01593707 14.98475364 18.83935253]
 [75.97964264 77.68295574 99.21815073]]


In [15]:
l5 = np.dot(l4, w5.T) + b5
print(l5)

[[ 34.50086663  15.53373736  16.68092372]
 [ 34.50086663  15.53373736  16.68092372]
 [178.55855996  77.38683292  85.26451102]]
