In [1]:
import numpy as np
from nnfs.datasets import spiral_data
import nnfs
import matplotlib.pyplot as plt

### Example of a `ReLU` Activation

In [2]:
input = np.array([0, -2, 1, 3.2, -2.7, 1.1, 2.2, -3])

In [3]:
output = np.maximum(0, input) # output[i] =  max(0, input[i])
print(output)

[0.  0.  1.  3.2 0.  1.1 2.2 0. ]


### Example of `Softmax` Activation

In [4]:
input = np.array([
    [1, 2, 3, 2.5],
    [2.0, 5.0, -1.0, 2],
    [-1.5, 2.7, 3.3, -0.8]
])

In [5]:
exp_values = np.exp(input - np.max(input, axis=1, keepdims=True))

In [6]:
probabilities = exp_values / np.sum(exp_values, axis=1, keepdims=True)

In [7]:
print(probabilities)
print(np.sum(probabilities, axis=1))

[[0.06414769 0.17437149 0.47399085 0.28748998]
 [0.04517666 0.90739747 0.00224921 0.04517666]
 [0.00522984 0.34875873 0.63547983 0.0105316 ]]
[1. 1. 1.]


### A complete pass through the network

In [8]:
class DenseLayer:
    def __init__(self, n_inputs, n_neurons):
        self.weights = 0.01 * np.random.randn(n_inputs, n_neurons)
        self.biases = np.zeros((1, n_neurons))

    def forward(self, inputs):
        self.outputs = np.dot(inputs, self.weights) + self.biases

In [9]:
class ReLU:
    def forward(self, inputs):
        self.outputs = np.maximum(0, inputs)

In [10]:
class Softmax:
    def forward(self, inputs):
        exp_values = np.exp(inputs - np.max(inputs, axis=1, keepdims=True))
        self.outputs = exp_values / np.sum(exp_values, axis=1, keepdims=True)

In [ ]:
nnfs.init() # init the class to create the dataset

In [12]:
x, y = spiral_data(samples=100, classes=3)

In [13]:
relu = ReLU() # Create objects of the activation classes
softmax = Softmax()

In [14]:
layer1 = DenseLayer(2, 3) # layer 1 has 2 inputs and 3 neurons

In [15]:
layer1.forward(x) # pass through the first layer

In [16]:
relu.forward(layer1.outputs) # pass through the ReLU activation

In [17]:
layer2 = DenseLayer(3, 3) # layer 2 has 3 inputs and 3 neurons

In [18]:
layer2.forward(relu.outputs) # pass through the second layer

In [19]:
softmax.forward(layer2.outputs)

In [20]:
print(softmax.outputs[:5])

[[0.33333334 0.33333334 0.33333334]
 [0.3333332  0.3333332  0.33333364]
 [0.3333329  0.33333293 0.3333342 ]
 [0.3333326  0.33333263 0.33333477]
 [0.33333233 0.3333324  0.33333528]]


In [ ]:
print(np.sum(softmax.outputs[:5], axis= 1, keepdims=True)) # Sums to 1

[[1.]
 [1.]
 [1.]
 [1.]
 [1.]]
